spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.8:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  output:
    ansi:
      enabled: always
  redis:
    host: 192.168.1.8
    port: 6379
    password:
#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell


weChat:
  mpAppId: wxab363e6d6cc47738
  mpAppSecret: 63eb5fede9b36668b7110bc4fffeb804
  mchId: 2332
  mchKey: 322
  keyPath: 323
  notifyUrl: 232323
  openAppId:
  openAppSecret:

projectUrl:
  weChatWpAuthorize: https://sherlock.natapp4.cc/
  weChatOpenAuthorize: https://sherlock.natapp4.cc/
  sellUrl: https://sherlock.natapp4.cc/
